In [3]:
import numpy as np
import pandas as pd

movies = pd.read_csv('tmdb-movies.csv')
movies.head()

#genres
#id
#keywords 
#original title
#overview
#cast
#director
movies.info()

movies = movies[['id','original_title','overview','genres','keywords','cast','director']]

# If movies is a list of strings
for movie in movies:
    print(movie)  # Each 'movie' here is a string, not a dictionary or DataFrame row


# movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ","") for i in x])
# movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ","") for i in x])
# movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
# movies['director'] = movies['director'].apply(lambda x:[i.replace(" ","") for i in x])
# movies.head()


# import pandas as pd
# import numpy as np

# Example DataFrame structure (if you haven't loaded it already)
# movies = pd.DataFrame({
#     'genres': [['Action', 'Adventure'], np.nan, ['Comedy'], ['Drama', 'Action']],
#     'keywords': [['Hero', 'Fight'], ['Love'], np.nan, ['Family', 'Friendship']],
#     'cast': [['Actor1', 'Actor2'], ['Actor3'], ['Actor4'], np.nan]
# })

# Ensure you handle NaN values while applying the functions
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else x)
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else x)
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x] if isinstance(x, list) else x)

# Check the results
print(movies)



import ast

# Iterate over each movie (check if it's a dict first)
for movie in movies:
    if isinstance(movie, dict):  # Only process if it's a dictionary
        # Check if 'genres', 'keywords', and 'cast' are strings that need to be converted to lists
        if isinstance(movie.get('genres'), str):
            movie['genres'] = ast.literal_eval(movie['genres'])  # Convert the string to a list
        if isinstance(movie.get('keywords'), str):
            movie['keywords'] = ast.literal_eval(movie['keywords'])  # Convert the string to a list
        if isinstance(movie.get('cast'), str):
            movie['cast'] = ast.literal_eval(movie['cast'])  # Convert the string to a list

        # Now remove spaces in the lists
        movie['genres'] = [i.replace(" ", "") for i in movie['genres']]
        movie['keywords'] = [i.replace(" ", "") for i in movie['keywords']]
        movie['cast'] = [i.replace(" ", "") for i in movie['cast']]


print(type(movies))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10866 non-null  int64
 1   imdb_id               10856 non-null  object
 2   popularity            10866 non-null  float64
 3   budget                10866 non-null  int64
 4   revenue               10866 non-null  int64
 5   original_title        10866 non-null  object
 6   cast                  10790 non-null  object
 7   homepage              2936 non-null   object
 8   director              10822 non-null  object
 9   tagline               8042 non-null   object
 10  keywords              9373 non-null   object
 11  overview              10862 non-null  object
 12  runtime               10866 non-null  int64
 13  genres                10843 non-null  object
 14  production_companies  9836 non-null   object
 15  release_date          10866 non-null  object
 16  vote_count            10866 non-null  int64
 17  vote_average          10866 non-null  float64
 18  release_year          10866 non-null  int64
 19  budget_adj            10866 non-null  float64
 20  revenue_adj           10866 non-null  float64
dtypes: float64(4), int64(6), object(11)
memory usage: 1.7+ MB
id
original_title
overview
genres
keywords
cast
director
           id                original_title  \
0      135397                Jurassic World
1       76341            Mad Max: Fury Road
2      262500                     Insurgent
3      140607  Star Wars: The Force Awakens
4      168259                     Furious 7
...       ...                           ...
10861      21            The Endless Summer
10862   20379                    Grand Prix
10863   39768           Beregis Avtomobilya
10864   21449        What's Up, Tiger Lily?
10865   22293      Manos: The Hands of Fate

                                                overview  \
0      Twenty-two years after the events of Jurassic ...
1      An apocalyptic story set in the furthest reach...
2      Beatrice Prior must confront her inner demons ...
3      Thirty years after defeating the Galactic Empi...
4      Deckard Shaw seeks revenge against Dominic Tor...
...                                                  ...
10861  The Endless Summer, by Bruce Brown, is one of ...
10862  Grand Prix driver Pete Aron is fired by his te...
10863  An insurance agent who moonlights as a carthie...
10864  In comic Woody Allen's film debut, he took the...
10865  A family gets lost on the road and stumbles up...

                                          genres  \
0      Action|Adventure|Science Fiction|Thriller
1      Action|Adventure|Science Fiction|Thriller
2             Adventure|Science Fiction|Thriller
3       Action|Adventure|Science Fiction|Fantasy
4                          Action|Crime|Thriller
...                                          ...
10861                                Documentary
10862                     Action|Adventure|Drama
10863                             Mystery|Comedy
10864                              Action|Comedy
10865                                     Horror

                                                keywords  \
0      monster|dna|tyrannosaurus rex|velociraptor|island
1       future|chase|post-apocalyptic|dystopia|australia
2      based on novel|revolution|dystopia|sequel|dyst...
3                  android|spaceship|jedi|space opera|3d
4                    car race|speed|revenge|suspense|car
...                                                  ...
10861                           surfer|surfboard|surfing
10862                          car race|racing|formula 1
10863                           car|trolley|stealing car
10864                                              spoof
10865                fire|gun|drive|sacrifice|flashlight

                                                    cast            director
0      Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...     Colin Trevorrow
1      Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...       George Miller
2      Shailene Woodley|Theo James|Kate Winslet|Ansel...    Robert Schwentke
3      Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...         J.J. Abrams
4      Vin Diesel|Paul Walker|Jason Statham|Michelle ...           James Wan
...                                                  ...                 ...
10861  Michael Hynson|Robert August|Lord 'Tally Ho' B...         Bruce Brown
10862  James Garner|Eva Marie Saint|Yves Montand|Tosh...  John Frankenheimer
10863  Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...      Eldar Ryazanov
10864  Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...         Woody Allen
10865  Harold P. Warren|Tom Neyman|John Reynolds|Dian...    Harold P. Warren

[10866 rows x 7 columns]
<class 'pandas.core.frame.DataFrame'>

In [4]:
# movies['overview'] = movies['overview'].apply(lambda x:x.split())
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] +movies['director'] 

movies.head()
#movies['cast'].apply(lambda x:[i.replace(" ","") for i in x])
# movies = pd.read_csv('tmdb-movies.csv')

new_df = movies[['id','original_title','tags']]
new_df
new_df.head()
new_df['tags'][0]

#new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())
# Apply lower() method only if x is a string
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower() if isinstance(x, str) else x)

# Check the results
print(new_df['tags'].head())  # Display the first few rows to verify the changes


new_df.head()

0    twenty-two years after the events of jurassic ...
1    an apocalyptic story set in the furthest reach...
2    beatrice prior must confront her inner demons ...
3    thirty years after defeating the galactic empi...
4    deckard shaw seeks revenge against dominic tor...
Name: tags, dtype: object

C:\Users\DIVYANSHI\AppData\Local\Temp\ipykernel_12200\2179460591.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower() if isinstance(x, str) else x)

,id,original_title,tags
0,135397,Jurassic World,twenty-two years after the events of jurassic ...
1,76341,Mad Max: Fury Road,an apocalyptic story set in the furthest reach...
2,262500,Insurgent,beatrice prior must confront her inner demons ...
3,140607,Star Wars: The Force Awakens,thirty years after defeating the galactic empi...
4,168259,Furious 7,deckard shaw seeks revenge against dominic tor...

In [5]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')



# Fill NaN values with an empty string
new_df['tags'] = new_df['tags'].fillna('')

# Apply CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')
vectors = cv.fit_transform(new_df['tags']).toarray()

# If you want to see the feature names
feature_names = cv.get_feature_names_out()

# Output the feature names and vector shape
print(len(feature_names))  # Number of unique features
print(vectors.shape)       # Shape of the transformed array



# # Drop rows with NaN values
# new_df = new_df.dropna(subset=['tags'])

# # Now apply CountVectorizer
# cv = CountVectorizer(max_features=5000, stop_words='english')
# X = cv.fit_transform(new_df['tags']).toarray()

# # Check the shape of the resulting array
# print(X.shape)  # This will give you the shape of the document-term matrix
vectors
vectors[0]
len(cv.get_feature_names_out())

C:\Users\DIVYANSHI\AppData\Local\Temp\ipykernel_12200\3735368063.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].fillna('')

5000
(10866, 5000)

5000

In [6]:
#!pip install nltk
import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

new_df['tags'][0]

stem("twenty-two years after the events of jurassic park, isla nublar now features a fully functioning dinosaur theme park, jurassic world, as originally envisioned by john hammond.action|adventure|science fiction|thrillermonster|dna|tyrannosaurus rex|velociraptor|islandchris pratt|bryce dallas howard|irrfan khan|vincent d'onofrio|nick robinsoncolin trevorrow")



new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\DIVYANSHI\AppData\Local\Temp\ipykernel_12200\1702462872.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

#cosine_similarity(vectors)

cosine_similarity(vectors).shape

similarity = cosine_similarity(vectors)

sorted(list(enumerate(similarity[0])),reverse = True,key = lambda x:x[1])[1:6]

In [ ]:
def recommend(movie):
    movie_index = new_df[new_df['original_title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)),reverse = True,key = lambda x:x[1])[1:6]
    for i in movies_list:
        print(new_df.iloc[i[0]].original_title)
# new_df[new_df == 'Avatar'].index
recommend('The Last Starfighter')

In [ ]:
import pickle

In [ ]:
pickle.dump(new_df,open('movies.pkl','wb'))

In [ ]:
new_df['original_title'].values

In [ ]:
pickle.dump(new_df.to_dict(),open('movie_dict.pkl','wb'))
pickle.dump(similarity,open('similarity.pkl','wb'))

In [11]:
#new_df.to_dict()